### ISSUE TITLE
Missing module/function docs

### ISSUE THREAD

**Issue by mnishiguchi** [cocoa-xu/tflite_beam#24]
Here are a list of blank documents as of 2023-03-14

module docs
- [x] TFLiteElixir (top-level module)
- [x] TFLiteElixir.Ops.Builtin.BuiltinResolver
- [x] TFLiteElixir.Coral

function docs
- [x] TFLiteElixir.reset_variable_tensor/1
- [x] TFLiteElixir.Coral.contains_edge_tpu_custom_op?/1
- [x] TFLiteElixir.Coral.dequantize_tensor/2
- [x] TFLiteElixir.Coral.edge_tpu_devices/0
- [x] TFLiteElixir.Coral.get_edge_tpu_context/1
- [x] TFLiteElixir.Coral.get_edge_tpu_context/2
- [x] TFLiteElixir.Coral.make_edge_tpu_interpreter/2
- [x] TFLiteElixir.FlatBufferModel.initialized/1
- [x] TFLiteElixir.Interpreter.get_signature_defs/1
- [x] TFLiteElixir.Interpreter.predict/2

**Comment by cocoa-xu** [comment]
Module docs and function docs are addressed in commits 7ff7352011be9717bbf2b7ee44847b98154ec601..accc2bbfa1fcde4c557c5208a4089b508e812531
