### ISSUE TITLE
TFLiteTensor.dims vs out_tensor.shape

### ISSUE THREAD

**Issue by mnishiguchi** [cocoa-xu/tflite_beam#25]
This is rather a question about accessing tensor fields.

As I play with the Super Resolution example, I notice there are two ways to access shape and type of a tensor and they seem to give the same result at least in the context of the example. I am wondering if there is a case where we have to use the functions. Depending on it, we might need to explain in the doc or to consider deprecating the functions.

```elixir
out_tensor.shape
# vs
TFLite.TFLiteTensor.dims(out_tensor)
```

```elixir
out_tensor.type
# vs
type = TFLite.TFLiteTensor.type(out_tensor)
```

**Comment by cocoa-xu** [comment]
Hi @mnishiguchi, I intend to also port TFLite in Erlang so I'll probably keep them for the completeness of the APIs for now. And I'll revisit this issue when the Erlang part is done. :)

**Comment by cocoa-xu** [comment]
> ```elixir
> out_tensor.type
> # vs
> type = TFLite.TFLiteTensor.type(out_tensor)
> ```
I think this should be okay as we also have the same thing in `:nx`.

```elixir
iex> tensor = Nx.iota({2,2})
iex> tensor.type
{:s, 64}
iex> Nx.type(tensor)
{:s, 64}
```

As for `TFLiteTensor.dims/1` vs `tensor.shape`, I'm thinking that keeping both, but `TFLiteTensor.dims/1` will behave the same as TFLite's C++ API, which gives tensor's dimension in an array, e.g., `[1, 224, 224, 3]`; while `tensor.shape` will follow `:nx`'s convention, which would return the dimensions in a tuple, e.g., `{1, 224, 224, 3}`. Furthermore, I'll add a `TFLiteTensor.shape/1` function to mirror what we have in `:nx`.

```elixir
iex> tflite_tensor.type
{:s, 64}
iex> TFLiteTensor.type(tflite_tensor)
{:s, 64}
iex> tflite_tensor.shape
{1, 224, 224, 3}
iex> TFLiteTensor.shape(tflite_tensor)
{1, 224, 224, 3}
iex> TFLiteTensor.dims(tflite_tensor)
[1, 224, 224, 3]
```
