### ISSUE TITLE
Getting "Runtime node closed unexpectedly - no connection" on example tpu notebook

### ISSUE THREAD

**Issue by dkuku** [cocoa-xu/tflite_beam#30]
Hi. I wanted to try it with coral but my livebook dies on the last cell in the tpu.livemd
I tried to run it as mix task but also getting 
```
[1]    55100 segmentation fault (core dumped)  mix classify_image -m /tmp/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflit
```
I have the coredump but it's 175MB in size

**Comment by cocoa-xu** [comment]
Hi @dkuku, which version of `tflite_elixir` was it in the `Notebook dependencies and setup` cell? And could you please let me know if you're on an x86_64 or aarch64 Linux? Thanks!

**Comment by dkuku** [comment]
I was using the latest master on intel. In the deps there is 0.1.5. On cpu it runs fine for me

**Comment by cocoa-xu** [comment]
Oh I kinda know what went wrong here. I haven't added reference counting mechanism to the `EdgeTPUContext` and related things. So Erlang dropped some resources while they are meant to live at least as long as the `Interpreter`. 

I'll fix this in the next version.

With that said, if you would like to test and see if it can communicate with your TPU, then the normal model also works on TPU (but not optimised). For example,

```bash
$ mix classify_image --model test/test_data/mobilenet_v2_1.0_224_inat_bird_quant.tflite \
  --input test/test_data/parrot.jpeg \
  --labels test/test_data/inat_bird_labels.txt \
  --use-tpu \
  --tpu usb
----INFERENCE TIME----
78.4ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.70703
```

**Comment by dkuku** [comment]
this works 👍🏻 
```
mix classify_image --model test/test_data/mobilenet_v2_1.0_224_inat_bird_quant.tflite \                                                                             1 ✘  1 ☑  3  
  --input test/test_data/parrot.jpeg \
  --labels test/test_data/inat_bird_labels.txt \
  --use-tpu \
  --tpu usb
----INFERENCE TIME----
713.8ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.70703
```

**Comment by cocoa-xu** [comment]
Hi @dkuku, v0.1.6 is out and it should work as expected!

**Comment by dkuku** [comment]
Thanks @cocoa-xu 
It works 🥳, Thanks.
